// 연봉 데이터 (만원 단위)
const salaryPercentile = [
    { percentile: "상위 0.1%", salary: 98798, description: "0.1%: 토스뱅크 1000-8586-9366 감사합니다. 🏆💸  " },
    { percentile: "상위 0.2%", salary: 41668, description: "0.2%: VIP 라운지에서 '요즘 힘드네'라고 말하는 중. 🍷" },
    { percentile: "상위 0.3%", salary: 32719, description: "0.3%: 회사에서 임원 대접 받기 시작, 하지만 스트레스도 3배. 💼" },
    { percentile: "상위 0.4%", salary: 28195, description: "0.4$: 주식 계좌에 1억 이상 있는데, 하루 변동폭이 월급 수준. 📊" },
    { percentile: "상위 0.5%", salary: 25269, description: "0.5%: 청약 넣을 때 '당첨되면 그냥 산다' 마인드. 🏗️" },
    { percentile: "상위 0.6%", salary: 23333, description: "0.6%: 압구정은 무리지만, 서초는 무리없을 것 같음. 🌆" },
    { percentile: "상위 0.7%", salary: 21820, description: "0.7%: 차는 국산 대형 세단, 하지만 수입차도 눈에 들어옴. 🚘" },
    { percentile: "상위 0.8%", salary: 20681, description: "0.8%: 부모님께 용돈 드릴 때 100만 원 단위로 생각함. 💵" },
    { percentile: "상위 0.9%", salary: 19802, description: "0.9%: 해외 직구할 때 관세 생각하면서 계산함. 📦" },
    { percentile: "상위 1.0%", salary: 19062, description: "1%: 편의점에서 1+1 행사 발견하면 그래도 반갑다. 🏷️" },
    { percentile: "상위2%", salary: 16532, description: "2%: 내가 사는 동네 부동산 가격은 네이버 뉴스에서 따로 다룸. 🏠" },
    { percentile: "상위3%", salary: 13889, description: "3%: 골프장 VIP 라운지에서 '요즘 힘드네'라고 말하는 중. ⛳" },
    { percentile: "상위4%", salary: 12408, description: "4%: 에르메스백은 기본, 이제 맞춤 정장으로 승부 본다. 👜" },
    { percentile: "상위5%", salary: 11407, description: "5%: 외제차는 기본이고, 번호판 한 자리수면 좀 더 인정받음. 🚗" },
    { percentile: "상위6%", salary: 10600, description: "6%: 강남 학군이 고민? 아니지, 해외 조기유학이 고민이지. ✈️" },
    { percentile: "상위7%", salary: 9960, description: "7%: 대기업 간부들끼리 와인 마시며 출퇴근 시간을 고민함. 🍷" },
    { percentile: "상위8%", salary: 9462, description: "8%: 명품 시계 가격이 아니라, 한정판 여부가 중요함. ⌚" },
    { percentile: "상위9%", salary: 9035, description: "9%: 카드 한도 신경 안 씀. 블랙카드가 해결해줌. 💳" },
    { percentile: "상위10%", salary: 8659, description: "10%: 이제 돈이 아닌, 내 시간과 자유가 더 소중함. ⏳" },
    { percentile: "상위11%", salary: 8327, description: "11%: 강남 살지는 않지만, 그래도 '준강남'은 됨. 🏙️" },
    { percentile: "상위12%", salary: 8024, description: "12%: 해외여행은 가지만, 비즈니스 클래스는 고민함. ✈️" },
    { percentile: "상위13%", salary: 7742, description: "13%: 스타벅스 다니지만, 리필 안 되는 건 피함. ☕" },
    { percentile: "상위14%", salary: 7477, description: "14%: 결혼식 축의금 10만 원 내는 게 부담스럽진 않음. 💵" },
    { percentile: "상위15%", salary: 7227, description: "15%: 청약 가점이지만, '언제 당첨되나'가 고민임. 🏢" },
    { percentile: "상위16%", salary: 6995, description: "16%: 중고차 살 때도 연식보다는 브랜드 먼저 봄. 🚘" },
    { percentile: "상위17%", salary: 6773, description: "17%: 네이버 쇼핑보다 백화점 오프라인 쇼핑이 익숙함. 🛍️" },
    { percentile: "상위18%", salary: 6562, description: "18%: 이마트보단 코스트코, 가성비보단 브랜드! 🛒" },
    { percentile: "상위19%", salary: 6360, description: "19%: 여행은 무조건 자유여행, 패키지는 아직 고민 중. 🌏" },
    { percentile: "상위20%", salary: 6169, description: "20%: 연말정산 환급금이 아니라, 세금 더 낼 게 걱정임. 🧾" },
    { percentile: "상위21%", salary: 5998, description: "21%: 술은 싼 소주보다 프리미엄 막걸리가 좋음. 🍶" },
    { percentile: "상위22%", salary: 5840, description: "22%: 운동은 PT 등록하지만, 꾸준히 가는 건 또 다른 문제. 🏋️‍♂️" },
    { percentile: "상위23%", salary: 5684, description: "23%: 카드값 보고 한숨 쉬지만, 그래도 다음 달엔 또 긁음. 💳" },
    { percentile: "상위24%", salary: 5536, description: "24%: 편의점에서 삼각김밥보단 샐러드를 고르는 삶. 🥗" },
    { percentile: "상위25%", salary: 5392, description: "25%: 카페에서 메뉴판 가격 한 번 더 보고 시킴. ☕" },
    { percentile: "상위26%", salary: 5254, description: "26%: 호텔 조식 먹을 땐 최대한 늦게 가서 점심까지 해결. 🍽️" },
    { percentile: "상위27%", salary: 5121, description: "27%: 전세보단 월세, 그래도 지하철 1시간 이상 출퇴근은 힘듦. 🚉" },
    { percentile: "상위28%", salary: 4996, description: "28%: 명품 신발보단 뉴발란스 or 아디다스 삼선 슬리퍼. 👟" },
    { percentile: "상위29%", salary: 4875, description: "29%: 점심값 1만 원 넘으면 고민, 하지만 배달은 포기 못 함. 🍜" },
    { percentile: "상위30%", salary: 4766, description: "30%: 아이폰 사고 싶은데, 갤럭시 공시지원금이 너무 착함. 📱" },
    { percentile: "상위31%", salary: 4657, description: "31%: 넷플릭스는 친구랑 같이, 디즈니+는 고민 중. 📺" },
    { percentile: "상위32%", salary: 4550, description: "32%: 편의점 샌드위치도 비싸서 편의점 도시락으로 바꿈. 🍱" },
    { percentile: "상위33%", salary: 4448, description: "33%: 택시는 비싸니까, 카카오T 블루 대신 일반택시 호출. 🚖" },
    { percentile: "상위34%", salary: 4348, description: "34%: 에어팟 프로가 갖고 싶지만, QCY가 가성비 갑. 🎧" },
    { percentile: "상위35%", salary: 4251, description: "35%: 쿠팡 로켓와우 가입 고민 중, 월 4,990원이 부담됨. 📦" },
    { percentile: "상위36%", salary: 4165, description: "36%: 가스비 아끼려고 겨울에도 이불 속에서만 생활. ❄️" },
    { percentile: "상위37%", salary: 4076, description: "37%: 삼겹살은 1인분이 아니라, 무조건 '인분 나누기 2' 🥩" },
    { percentile: "상위38%", salary: 3992, description: "38%: 치킨 브랜드가 아니라, 치킨 할인 이벤트가 중요함. 🍗" },
    { percentile: "상위39%", salary: 3909, description: "39%: 외식보단 집밥, 간편식도 1+1 때만 구입. 🍛" },
    { percentile: "상위40%", salary: 3830, description: "40%: 데이터 무제한 요금제? Wi-Fi 없으면 그냥 참음. 📶" },
    { percentile: "상위41%", salary: 3751, description: "42%: 라면은 신라면, 컵라면은 오뚜기 세일할 때만. 🍜" },
    { percentile: "상위42%", salary: 3675, description: "42%: 라면은 신라면, 컵라면은 오뚜기 세일할 때만. 🍜" },
    { percentile: "상위43%", salary: 3608, description: "44%: 넷플릭스? 무료체험 돌려막기. 🎥" },
    { percentile: "상위44%", salary: 3546, description: "46%: 국밥 한 그릇으로 두 끼 해결 가능. 🍲" },
    { percentile: "상위45%", salary: 3479, description: "46%: 국밥 한 그릇으로 두 끼 해결 가능. 🍲" },
    { percentile: "상위46%", salary: 3413, description: "48%: 통신비 아끼려고 데이터 무제한 포기. 📶" },
    { percentile: "상위47%", salary: 3349, description: "48%: 통신비 아끼려고 데이터 무제한 포기. 📶" },
    { percentile: "상위48%", salary: 3285, description: "50%: 택시요금 100원 차이에도 어플 비교 중. 🚕" },
    { percentile: "상위49%", salary: 3225, description: "50%: 택시요금 100원 차이에도 어플 비교 중. 🚕" },
    { percentile: "상위50%", salary: 3165, description: "52%: 치킨 한 마리는 사치, 닭가슴살이 가성비 갑. 🍗" },
    { percentile: "하위51%", salary: 3105, description: "52%: 치킨 한 마리는 사치, 닭가슴살이 가성비 갑. 🍗" },
    { percentile: "하위52%", salary: 3045, description: "54%: 카페? 이디야 아니면 믹스커피지. ☕" },
    { percentile: "하위53%", salary: 2995, description: "54%: 카페? 이디야 아니면 믹스커피지. ☕" },
    { percentile: "하위54%", salary: 2942, description: "56%: 점심은 무조건 김밥천국 or 편의점 도시락. 🍱" },
    { percentile: "하위55%", salary: 2887, description: "56%: 점심은 무조건 김밥천국 or 편의점 도시락. 🍱" },
    { percentile: "하위56%", salary: 2834, description: "58%: 운동? 헬스장 비싸서 집에서 홈트 함. 🏋️‍♂️" },
    { percentile: "하위57%", salary: 2779, description: "58%: 운동? 헬스장 비싸서 집에서 홈트 함. 🏋️‍♂️" },
    { percentile: "하위58%", salary: 2728, description: "60%: 버스 환승 2번까지는 감수할 수 있음. 🚌" },
    { percentile: "하위59%", salary: 2676, description: "60%: 버스 환승 2번까지는 감수할 수 있음. 🚌" },
    { percentile: "하위60%", salary: 2628, description: "62%: 컵라면 큰 거 사느니 작은 거 두 개 사는 게 이득. 🍜" },
    { percentile: "하위61%", salary: 2578, description: "62%: 컵라면 큰 거 사느니 작은 거 두 개 사는 게 이득. 🍜" },
    { percentile: "하위62%", salary: 2530, description: "64%: 편의점 1+1 아니면 절대 안 삼. 🏷️" },
    { percentile: "하위63%", salary: 2487, description: "64%: 편의점 1+1 아니면 절대 안 삼. 🏷️" },
    { percentile: "하위64%", salary: 2438, description: "66%: 택시? 그냥 지하철+버스+도보 콤보로 해결. 🚶‍♂️" },
    { percentile: "하위65%", salary: 2402, description: "66%: 택시? 그냥 지하철+버스+도보 콤보로 해결. 🚶‍♂️" },
    { percentile: "하위66%", salary: 2376, description: "68%: 할인마트에서 유통기한 임박 제품 찾기 고수. 🛒" },
    { percentile: "하위67%", salary: 2330, description: "68%: 할인마트에서 유통기한 임박 제품 찾기 고수. 🛒" },
    { percentile: "하위68%", salary: 2300, description: "70%: 무료 나눔 & 줍줍이 쇼핑의 일부. 🎁" },
    { percentile: "하위69%", salary: 2271, description: "70%: 무료 나눔 & 줍줍이 쇼핑의 일부. 🎁" },
    { percentile: "하위70%", salary: 2210, description: "72%: 편의점? 이젠 시장 가야 함. 🏬" },
    { percentile: "하위71%", salary: 2149, description: "72%: 편의점? 이젠 시장 가야 함. 🏬" },
    { percentile: "하위72%", salary: 2078, description: "74%: 월세 살면서 가스비 아끼려고 이불 두 겹 씀. 🛏️" },
    { percentile: "하위73%", salary: 2006, description: "74%: 월세 살면서 가스비 아끼려고 이불 두 겹 씀. 🛏️" },
    { percentile: "하위74%", salary: 1930, description: "76%: 노트북? 중고 맥북 2015년형 아직 씀. 💻" },
    { percentile: "하위75%", salary: 1854, description: "76%: 노트북? 중고 맥북 2015년형 아직 씀. 💻" },
    { percentile: "하위76%", salary: 1785, description: "80%: 이제 외식은 꿈도 못 꾼다. 🍽️" },
    { percentile: "하위77%", salary: 1709, description: "78%: 데이터 무제한? Wi-Fi 없으면 그냥 포기. 📶" },
    { percentile: "하위78%", salary: 1629, description: "78%: 데이터 무제한? Wi-Fi 없으면 그냥 포기. 📶" },
    { percentile: "하위79%", salary: 1549, description: "80%: 이제 외식은 꿈도 못 꾼다. 🍽️" },
    { percentile: "하위80%", salary: 1470, description: "80%: 이제 외식은 꿈도 못 꾼다. 🍽️" },
    { percentile: "하위81%", salary: 1399, description: "82%: 겨울에도 전기장판 없이 버팀. 🥶" },
    { percentile: "하위82%", salary: 1315, description: "82%: 겨울에도 전기장판 없이 버팀. 🥶" },
    { percentile: "하위83%", salary: 1232, description: "82%: 겨울에도 전기장판 없이 버팀. 🥶" },
    { percentile: "하위84%", salary: 1175, description: "84%: 집밥 말고는 대안이 없다. 🍚" },
    { percentile: "하위85%", salary: 1095, description: "84%: 집밥 말고는 대안이 없다. 🍚" },
    { percentile: "하위86%", salary: 1011, description: "86%: 옷? 무조건 중고 or 기부받음. 👕" },
    { percentile: "하위87%", salary: 935, description: "88%: 배달음식? 그건 상위 20%의 삶이지. 🚴‍♂️" },
    { percentile: "하위88%", salary: 855, description: "88%: 배달음식? 그건 상위 20%의 삶이지. 🚴‍♂️" },
    { percentile: "하위89%", salary: 778, description: "90%: 이제 지하철 마저 사치로 느껴짐. 🏃" },
    { percentile: "하위90%", salary: 710, description: "90%: 이제 지하철 마저 사치로 느껴짐. 🏃" },
    { percentile: "하위91%", salary: 633, description: "92%: 빵이 한 끼 해결 가능. 🍞" },
    { percentile: "하위92%", salary: 569, description: "92%: 빵이 한 끼 해결 가능. 🍞" },
    { percentile: "하위93%", salary: 493, description: "94%: 컵라면도 특가 상품 아니면 고민함. 🍜" },
    { percentile: "하위94%", salary: 420, description: "94%: 컵라면도 특가 상품 아니면 고민함. 🍜" },
    { percentile: "하위95%", salary: 356, description: "94%: 컵라면도 특가 상품 아니면 고민함. 🍜" },
    { percentile: "하위96%", salary: 283, description: "96%: 이젠 경제 뉴스 볼 필요 없음. 어차피 내 이야기 아님. 📰" },
    { percentile: "하위97%", salary: 216, description: "96%: 이젠 경제 뉴스 볼 필요 없음. 어차피 내 이야기 아님. 📰" },
    { percentile: "하위98%", salary: 155, description: "98%: 전기세 아끼려고 카톡도 최소한으로 씀. 📵" },
    { percentile: "하위99%", salary: 87, description: "98%: 전기세 아끼려고 카톡도 최소한으로 씀. 📵" },
    { percentile: "하위100%", salary: 21, description: "100%: 돈이 아니라 체력이 전 재산. 🏃‍♂️" },
];

document.addEventListener("DOMContentLoaded", function() {
    document.getElementById('salary-form').addEventListener('submit', function (event) {
        event.preventDefault();
        const salary = Number(document.getElementById('salary').value);
        if (isNaN(salary) || salary <= 0) {
            document.getElementById('result').innerText = "올바른 연봉을 입력하세요.";
            return;
        }
        const matchedData = salaryPercentile.find(p => salary >= p.salary);
        const percentile = matchedData?.percentile || "하위 100%";
        const description = matchedData?.description || " 계좌번호 남겨주세요.. 🤔";
        // document.getElementById('result').innerText = `당신의 연봉은 ${percentile}에 해당합니다. ${description}`;
        document.getElementById('result').innerHTML = `당신의 연봉은 <br><strong>${percentile}</strong>에 해당합니다.<hr>${description}`;

    });
});
